# Generated by Django 5.0.1 on 2024-01-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_slug_alter_products_category'),
        ('suppliers', '0002_alter_supplier_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='suppliers',
            field=models.ManyToManyField(to='suppliers.supplier'),
        ),
    ]
