# Generated by Django 5.0.1 on 2024-01-29 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_slug_alter_products_category'),
        ('suppliers', '0002_alter_supplier_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.supplier')),
            ],
            options={
                'verbose_name': 'Fornecedor do produto',
                'verbose_name_plural': 'Fornecedores dos Produtos',
                'unique_together': {('supplier', 'product')},
            },
        ),
        migrations.AddField(
            model_name='products',
            name='suppliers',
            field=models.ManyToManyField(through='products.SupplierProduct', to='suppliers.supplier'),
        ),
    ]
