# Generated by Django 5.0.1 on 2024-02-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_supplierproduct_products_suppliers'),
        ('suppliers', '0002_alter_supplier_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supplierproduct',
            unique_together={('supplier', 'product', 'id')},
        ),
        migrations.AlterField(
            model_name='products',
            name='suppliers',
            field=models.ManyToManyField(blank=True, through='products.SupplierProduct', to='suppliers.supplier'),
        ),
    ]
